### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Goobrr**

### CODE REVIEW

**Comment by KayWasTaken** [comment]
gaming

**Comment by Goobrr** [comment]
the json comments might break stuff but i had to leave some notes. Remove them if you need to

**Comment by staticalliam7** [comment]
👍 Don't worry about the scripts, they are not finished yet. Should probably move them to a different branch

**Comment by staticalliam7** [comment]
also, borrowed code wasn't changed because I got distracted and never fixed anything

**Pull request merged**
